# Generated by Django 4.0.5 on 2022-06-13 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlotDadosDatabaseteste',
        ),
    ]
